### ISSUE TITLE
Feature Request: multi-language support

### ISSUE THREAD

**Issue by Mekako** [marvinody/amiami#2]
First of all, thank you for your tool, it has saved me a lot of time. 
However, I would like to add a feature for switching between English and Japanese. 
Can you help me with that?

**Comment by marvinody** [comment]
I'm unsure of what exactly you're asking for. I know there exists an amiami JP site, are you asking to support looking up on that?

If you can add more details on what you would like and maybe URLs to be clear of which websites then I can take a peek at if I can do anything.

**Comment by Mekako** [comment]
> I'm unsure of what exactly you're asking for. I know there exists an amiami JP site, are you asking to support looking up on that?
> 
> If you can add more details on what you would like and maybe URLs to be clear of which websites then I can take a peek at if I can do anything.

Sorry for not making it clear. 
In short, I want to get the Janpanese name of goods.

**Comment by marvinody** [comment]
Looking at the amiami API response, it doesn't seem like they return the japanese name for the few goods I searched for. So it's not looking for doable for the feature you asked for. Sorry

**Comment by Mekako** [comment]
![image](https://github.com/marvinody/amiami/assets/113497377/a33f25be-f394-4a3d-b5fd-0677591d3c25)
I tried to change your code here from 'eng' to 'jpn'.
And it worked well. It returned the janpanese name of what I searched for.
![image](https://github.com/marvinody/amiami/assets/113497377/aaedfccd-5f0d-456d-9abe-164fb638063a)
That's enough for me now.
Thanks again for your work!
